# Build configuration is generated by ./configure, which writes config.mk.
# Run './configure --help' for available options (prefix, libdir, module
# name, NSS types, etc.).
#
# config.mk is -include'd below so a plain 'make' will just build an object.
# Relevant make variables (all overridable):
#
#   PREFIX   Installation prefix            [default: /usr/local]
#   LIBDIR   Library installation directory [default: $(PREFIX)/lib/]
#   DESTDIR  Staging root for package builds [default: empty]
#   CFLAGS   Compiler flags - export from the environment or set on the
#            command line.  Required flags are always present.
#   LDFLAGS  Linker flags - export from the environment or set on the
#            command line.  Required flags are always present.
#
# Examples:
#   ./configure --prefix=/usr --with-types=pwd,grp,hosts && make
#   export CFLAGS="-O0 -ggdb3" && ./configure --prefix=/usr && make
#   make PREFIX=/usr DESTDIR=/tmp/staging install

-include config.mk

# ---------------------------------------------------------------------------
# Installation paths and prefixes
# ---------------------------------------------------------------------------
PREFIX ?= /usr/local
LIBDIR ?= $(PREFIX)/lib/
MODULE_NAME ?= altfiles
DATADIR ?= $(PREFIX)/lib/

# ---------------------------------------------------------------------------
# Feature flags set by configure or on the command line.
#
# pwd, grp, and initgroups are on by default; all others are opt-in.
#
# Any value means enabled.
# Empty value means disabled.
# ---------------------------------------------------------------------------
HANDLE_pwd        ?= 1
HANDLE_grp        ?= 1
HANDLE_initgroups ?= 1
HANDLE_spwd       ?=
HANDLE_sgrp       ?=
HANDLE_hosts      ?=
HANDLE_network    ?=
HANDLE_service    ?=
HANDLE_proto      ?=
HANDLE_rpc        ?=

# ---------------------------------------------------------------------------
# Library target name
# ---------------------------------------------------------------------------
TARGET := libnss_$(strip $(MODULE_NAME)).so.2

# ---------------------------------------------------------------------------
# Object list
#
# Each HANDLE_XXX maps to exactly one primary TU (files-XXX.o) plus any
# helper objects that TU depends on at link time.
# The initgroups TU shares the grp helper (fgetgrent_r.o).
# ---------------------------------------------------------------------------
OBJS :=
OBJS += src/malloc/alloc_buffer_alloc_array.o
OBJS += src/malloc/alloc_buffer_allocate.o
OBJS += src/malloc/alloc_buffer_copy_bytes.o
OBJS += src/malloc/alloc_buffer_copy_string.o
OBJS += src/malloc/alloc_buffer_create_failure.o
OBJS += src/malloc/dynarray_emplace_enlarge.o
OBJS += src/malloc/scratch_buffer_grow.o
OBJS += $(if $(HANDLE_rpc),        src/nss/nss_files/files-rpc.o)
OBJS += $(if $(HANDLE_proto),      src/nss/nss_files/files-proto.o)
OBJS += $(if $(HANDLE_hosts),      src/nss/nss_files/files-hosts.o)
OBJS += $(if $(HANDLE_network),    src/nss/nss_files/files-network.o)
OBJS += $(if $(HANDLE_service),    src/nss/nss_files/files-service.o)
OBJS += $(if $(HANDLE_pwd),        src/nss/nss_files/files-pwd.o src/nss/fgetpwent_r.o)
OBJS += $(if $(HANDLE_grp),        src/nss/nss_files/files-grp.o src/nss/fgetgrent_r.o)
OBJS += $(if $(HANDLE_initgroups), src/nss/nss_files/files-initgroups.o src/nss/fgetgrent_r.o)
OBJS += $(if $(HANDLE_spwd),       src/nss/nss_files/files-spwd.o src/nss/sgetspent_r.o)
OBJS += $(if $(HANDLE_sgrp),       src/nss/nss_files/files-sgrp.o src/nss/sgetsgent_r.o)
OBJS := $(sort $(OBJS))

# ---------------------------------------------------------------------------
# Shared dependencies
#
# Headers, inline sources, and template sources that every TU depends on.
# Touching any of these triggers a full rebuild, which is correct given
# their impact across the source tree.
# ---------------------------------------------------------------------------
SHARED_HEADERS := $(wildcard src/include/*.h) $(wildcard src/include/**/*.h)
SHARED_HEADERS += $(wildcard src/include/*.c) $(wildcard src/include/**/*.c)
SHARED_HEADERS += $(wildcard src/nss/resolv/*.h)

SHARED_SOURCE  := src/nss/nss_files/files-XXX.c
SHARED_SOURCE  += src/nss/nss_files/files-parse.c

# ---------------------------------------------------------------------------
# Compiler flags
#
# _REQ_CFLAGS are non-negotiable for this shared library and are prepended
# via 'override' so they survive a command-line CFLAGS= assignment.  The
# caller's flags are still honoured — they just cannot evict what is needed.
#
# Default to rational CFLAGS if none are provided.
# ---------------------------------------------------------------------------
_REQ_CFLAGS := -pthread -fPIC -std=gnu11 -D_GNU_SOURCE
_REQ_CFLAGS += -ffunction-sections
_REQ_CFLAGS += -Isrc -Isrc/include -Isrc/malloc -Isrc/nss
_REQ_CFLAGS += -include src/compat/altfiles_glibc_compat.h
_REQ_CFLAGS += -DALTFILES_MODULE_NAME=$(strip $(MODULE_NAME))
_REQ_CFLAGS += -DALTFILES_DATADIR='"$(strip $(DATADIR))"'

CFLAGS ?= -O2 -g -Wall -Wno-unused-parameter -Wformat=2
override CFLAGS := $(_REQ_CFLAGS) $(CFLAGS)

# ---------------------------------------------------------------------------
# Linker flags
#
# _SO_LDFLAGS are specific to the shared library (soname, symbol versioning)
# and must not be applied to plain executables.
#
# Default to rational LD_FLAGS if none are provided.
# ---------------------------------------------------------------------------
_SO_LDFLAGS := -Wl,-soname,$(TARGET)
_SO_LDFLAGS += -Wl,--version-script=src/compat/altfiles_symbols.map
_REQ_LDFLAGS += -Wl,--gc-sections -Wl,-z,relro -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl,-z,now

LDFLAGS ?=
override LDFLAGS := $(_REQ_LDFLAGS) $(LDFLAGS)

# ---------------------------------------------------------------------------
# Targets
# ---------------------------------------------------------------------------

.PHONY: all check clean distclean install

all: $(TARGET) nss-altfiles-config

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) $(_SO_LDFLAGS) -shared -o $@ $^

nss-altfiles-config: src/nss-altfiles-config.o
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

install: $(TARGET) nss-altfiles-config
	install -m 755 -d $(DESTDIR)$(LIBDIR)
	install -m 755 $(TARGET) $(DESTDIR)$(LIBDIR)$(TARGET)
	install -m 755 -d $(DESTDIR)$(PREFIX)/bin/
	install -m 755 nss-altfiles-config $(DESTDIR)$(PREFIX)/bin/nss-altfiles-config

check:
	@echo "No tests are defined"
	exit 1

clean:
	find src -name '*.o' -delete
	$(RM) $(TARGET) nss-altfiles-config

distclean: clean
	$(RM) config.mk

# ---------------------------------------------------------------------------
# Per-TU compile rules
#
# Each primary TU (files-XXX.o) is compiled with -DHANDLE_XXX so that the
# static symbols instantiated from files-XXX.c are local to that object and
# do not collide when the objects are linked into the shared library.
#
# Helper TUs (fgetpwent_r.o, fgetgrent_r.o, etc.) export plain functions.
#
# The $(if $(HANDLE_XXX), $(eval ...)) guards mirror the OBJS list exactly:
# disabled types produce no rule and are never compiled.
# ---------------------------------------------------------------------------

# compile_tu(obj, src, type)
#   Generates an explicit rule that compiles <src> into <obj> with -DHANDLE_<type>.
#   $$@ and $$< use double-dollar to defer expansion until after eval.
define compile_tu
$(1): $(2) $(SHARED_HEADERS) $(SHARED_SOURCE)
	$$(CC) $$(CFLAGS) -DHANDLE_$(strip $(3)) -c -o $$@ $$<
endef

$(if $(HANDLE_pwd),        $(eval $(call compile_tu, src/nss/nss_files/files-pwd.o,        src/nss/nss_files/files-pwd.c,        pwd)))
$(if $(HANDLE_grp),        $(eval $(call compile_tu, src/nss/nss_files/files-grp.o,        src/nss/nss_files/files-grp.c,        grp)))
$(if $(HANDLE_initgroups), $(eval $(call compile_tu, src/nss/nss_files/files-initgroups.o, src/nss/nss_files/files-initgroups.c, initgroups)))
$(if $(HANDLE_spwd),       $(eval $(call compile_tu, src/nss/nss_files/files-spwd.o,       src/nss/nss_files/files-spwd.c,       spwd)))
$(if $(HANDLE_sgrp),       $(eval $(call compile_tu, src/nss/nss_files/files-sgrp.o,       src/nss/nss_files/files-sgrp.c,       sgrp)))
$(if $(HANDLE_hosts),      $(eval $(call compile_tu, src/nss/nss_files/files-hosts.o,      src/nss/nss_files/files-hosts.c,      hosts)))
$(if $(HANDLE_network),    $(eval $(call compile_tu, src/nss/nss_files/files-network.o,    src/nss/nss_files/files-network.c,    network)))
$(if $(HANDLE_service),    $(eval $(call compile_tu, src/nss/nss_files/files-service.o,    src/nss/nss_files/files-service.c,    service)))
$(if $(HANDLE_proto),      $(eval $(call compile_tu, src/nss/nss_files/files-proto.o,      src/nss/nss_files/files-proto.c,      proto)))
$(if $(HANDLE_rpc),        $(eval $(call compile_tu, src/nss/nss_files/files-rpc.o,        src/nss/nss_files/files-rpc.c,        rpc)))

src/nss-altfiles-config.o: src/nss-altfiles-config.c $(SHARED_HEADERS)
	$(CC) $(CFLAGS) -c -o $@ $<
