#! /bin/bash
#
# dlfiles
# Copyright (C) 2013-2014 Adrian Perez <aperez@igalia.com>
#
# Distributed under terms of the MIT license.
#
set -eu

declare -r DIST_URL_BASE='http://ftp.gnu.org/gnu/glibc/'

if [[ $# -ne 1 ]] ; then
	cat <<-EOF
	Usage: $0 version
	EOF
	exit 1
fi 1>&2

version=$1

if [[ ! -d glibc-${version} ]] ; then
	if [[ ! -r glibc-${version}.tar.xz ]] ; then
		echo "fetching ${DIST_URL_BASE}/glibc-${version}.tar.xz ..."
		wget "${DIST_URL_BASE}/glibc-${version}.tar.xz"
	fi
	echo "Unpacking glibc-${version}.tar.xz ..."
	tar -xJf glibc-${version}.tar.xz
fi

while IFS= read -r -d '' dst_file; do
    dst_file_name=${dst_file##*/}

    mapfile -t matches < <(find "glibc-${version}" -name "${dst_file_name}")

    if (( ${#matches[@]} == 0 )); then
        echo "Skipping ${dst_file_name} (no glibc counterpart)"
        continue
    fi

    if (( ${#matches[@]} > 1 )); then
        echo "Skipping ${dst_file_name} (ambiguous: ${matches[*]})" >&2
        continue
    fi

    cp -v "${matches[0]}" "${dst_file}"
done < <(find src/ \( -name '*.c' -o -name '*.h' \) -print0)
